### ISSUE TITLE
変更点

### ISSUE THREAD

**Issue by unison-hasimoto** [up-codes/abisu-css#10]
何が変更されたのかをざっくりでもいいので書くように。
コードの差分を確認していくのはちょっと難しい。

**Comment by sekikawa-unison** [comment]
こちらにざっくり記載しておきました！
わかりにくかったらまたおっしゃてください

https://unisonplanet.notepm.jp/page/d3069c8eb1

**Comment by unison-hasimoto** [comment]
@sekikawa-unison 
なるほど、そちらですね！
