### ISSUE TITLE
match height

### ISSUE THREAD

**Issue by unison-hasimoto** [up-codes/abisu-css#12]
25行目〜34行目を削除
htmlのdata属性、【data-mh=""】もしくは【data-mh="hoge"】のように設定すれば動作する

**Comment by sekikawa-unison** [comment]
ありがとうございます！

```
// match height
$(function () {
  if (edit_design_check == -1) {
    $(window).on('load', function () {
      $('.match_01').matchHeight();
      $('.match_02').matchHeight();
      $('.match_03').matchHeight();
    });
  }
});
```

田中さんこれって、
data属性を設定するのがめんどくさいからclassで書きたい、
同じページでも同じクラス.match_01を併用しても問題ない

という意図で設定していた感じですよね？
@unisontanaka

**Comment by unisontanaka** [comment]
@sekikawa-unison 
そうです！
クラス名のほうがわかりやすいかと思いまして。

**Comment by sekikawa-unison** [comment]
ありがとうございます！

ちょっと悩ましいですが、
一旦削除して、各々好きな形で実装していただく感じにしたいと思います。
