### ISSUE TITLE
up-col系

### ISSUE THREAD

**Issue by unison-hasimoto** [up-codes/abisu-css#17]
アイテムをフレックスで言うところの、
justify-content: center;的なのは、どうすればできるのか。

また、管理画面用のcssは変更の必要はありませんか。

**Comment by sekikawa-unison** [comment]
>アイテムをフレックスで言うところの、
justify-content: center;的なのは、どうすればできるのか。

たしかにですね。。
gridではそういうのはできなさそうなので
そもそもup-col-系をgridにするのは違っていたかもですね。

一覧の実装でgrid使わないならフレームワーク化するほどじゃないかもしれないですね。

>また、管理画面用のcssは変更の必要はありませんか。

abisu.cssのことですかね。少し変更加えました。

**Comment by sekikawa-unison** [comment]
とりあえずup-col系は従来のflexに戻し、up-gapxとup-gapyもそのままの残し、row-gapだけフレームワーク化してみます。
