### ISSUE TITLE
.up-left/right-〇〇の汎用性

### ISSUE THREAD

**Issue by k-yoshida-unisonplanet** [up-codes/abisu-css#19]
現在、
.up-left-1000,
.up-left-1200・・・などで
margin-left: calc(50% - 500px);
margin-left: calc(50% - 600px);・・・などと指定されていますが、
margin-left: calc(50% - 50vw); とすれば、inner幅にかかわらず左右ベタ付けにしてくれます。

例

[class*=up-left-"]  { 
margin-left: calc(50% - 50vw);
}
[class*=up-right-"]  { 
margin-right: calc(50% - 50vw);
}

これで全inner幅可変で対応できるかと思います。

**Comment by sekikawa-unison** [comment]
確認しておきます！

issue作ったらlabelとprojectsを設定しておいてください！

**Comment by k-yoshida-unisonplanet** [comment]
calc(50% - 50vw);を使うのはinner幅がある前提だったため、変更必要なし
