### ISSUE TITLE
ディレクトリ構成

### ISSUE THREAD

**Issue by unison-hasimoto** [up-codes/abisu-css#20]
■一点目
コーディングで必要なファイルに限定しzipデータをダウンロードできた方がシンプルな構成と思われる。
つまり、stylusなどのデータはフレームワークを構築するために必要なデータでなので、
単純なコーディングに必要なデータに限定してzip化した方がシンプルだと思われる。
フレームワーク構築用のzipデータと、コーディングする用のzipデータを分ける形。

■二点目
さらに、node.jsやgulpを利用しない環境用のzipデータも用意した方が良いと思われる。
そのような環境を活用できない人、もしくは、利用できない人も少なからず存在する、
平たくいえばハードルが高いということ。
あくまでもプラスアルファの要素として捉えた方が良いと思われる。

最終的なzipデータの種類としては下記の種類が望ましいと思われる。
・フレームワーク構築用
・単純なコーディング用
・単純なコーディング用＋node.jsやgulp環境用

**Comment by sekikawa-unison** [comment]
zipを分けるというのは厳しいですが、単純なコーディング用で使いたい方はabisu-cssフォルダではなくその直下のhtmlフォルダのみ使用すれば良いかと
単純なコーディングに不要なものは全てhtmlフォルダの外に置いておきました

**Comment by unisontanaka** [comment]
先ほど神野くん用にzipをダウンロードしたのですが橋本さんのおっしゃるようにわけられているほうが助かります。
ですが複数のzipを用意するのはGitHubの仕様的に難しそうなのでひとまず現状でいってみて、他に良い方法や考え方があればそっちを検討するのはどうでしょうか？

**Comment by sekikawa-unison** [comment]
おっしゃる通りGitで管理してるので難しいかなと

その場合もう一つ別のリポジトリを作るしかないかなと思います。

**Comment by sekikawa-unison** [comment]
でももしかしたらgulpで複数箇所にコンパイルしたcssを生成できるかもしれないので考えてみます！
