### ISSUE TITLE
ベンプレ

### ISSUE THREAD

**Issue by unison-hasimoto** [up-codes/abisu-css#8]
-ms-のついたものが見受けられる<br>
IEのためのベンプレをつけないようにすることと、<br>
autoprefixerの設定を見直す必要があると思われる。

**Comment by k-yoshida-unisonplanet** [comment]
ベンダーは以下のプロパティ必要ないみたいなので、この機会に減らせるものは減らしたいなと。
・animation
・border-image
・border-radius
・box-shadow
・box-sizing
・text-shadow
・transform
・transition
・@keyframes

https://qiita.com/amamamaou/items/42197e443134478befaf

**Comment by sekikawa-unison** [comment]
- シェアが5%以上
- 最新版から2個前まで
- サポートが終了していない
- Android4以上

という条件でベンダーのオプションを調整します

safari8以上というオプションが付いてたんですが削除することで200行くらい節約
ieを考慮しなくなり200行くらい節約

**Comment by unison-hasimoto** [comment]
@up-codes/unisonplanet 

closeしたけど気になったので失礼します。

- シェアが5%以上
- 最新版から2個前まで
- サポートが終了していない
- Android4以上

この条件に選定した意図を知りたいです。
（どのブラウザ、どのバージョンをカバーすることを想定したのかということです）

また、ブラウザのカバー範囲はどこでシミュレーションしましたか？
ブラウザリストは、どの時点のリストを基にするかでカバーする範囲も変わると思いますが。

ブラウザのシェア率
https://gs.statcounter.com/browser-market-share

皆んなも知っているサイトで簡易的にシミュレーションできる
https://caniuse.com/ciu/browserset

**Comment by sekikawa-unison** [comment]
ありがとございます！

5%と書かれていた記事が多かったので安易に数字をいじってしましました。。

もともと2%の設定だったので戻した方が良さそうですね
